### ISSUE TITLE
500 Error bug

### ISSUE THREAD

**Issue by ablwr** [MediaArea/MediaConchOnline#69]
This is hard to replicate, but sometimes when I initially load the MediaConchOnline site, a 500 Error appears. When I refresh or navigate to another page, it goes away! Not sure what is causing the initial error which could alarm new users.
<img width="1155" alt="screen shot 2016-11-01 at 18 51 51" src="https://cloud.githubusercontent.com/assets/3260492/19910598/77b8afc4-a064-11e6-8e80-a81013625e6a.png">

**Comment by GuillaumeRoques** [comment]
Thanks, it has been fixed and deployed on prod.

**Comment by ablwr** [comment]
Thanks! Glad you were able to replicate the issue!
