### ISSUE TITLE
Invalid expression when creating is-equal rule 

### ISSUE THREAD

**Issue by ablwr** [MediaArea/MediaConchOnline#95]
Reported to me by @sallain:

Sara created a policy and rule using MediaConchOnline and exports the policy, which looks like this:

```
<?xml version="1.0"?>
<policy type="and" name="MP4 check" license="CC-BY-SA-4.0+">
  <rule name="Is MP4" value="Format" tracktype="General" occurrence="*" operator="Is equal (=)">MPEG-4</rule>
</policy>
```

But if trying to run this policy, it fails because it is expecting the operation to equal literal "=" instead of the human-friendly "Is equal (=)"

Error is
```
Validation generated an internal error:    Invalid expression
    compilation error: element when
    xsl:when : could not compile test expression 'mi:MediaInfo/mi:track[@type='General'][*]/mi:FormatIs equal (=)'MPEG-4''
```

**Comment by JeromeMartinez** [comment]
Issue confirmed with the online version, the GUI has not this issue.

**Comment by ablwr** [comment]
That's why I chose this repo ;)

**Comment by GuillaumeRoques** [comment]
Error have been fixed and deployed on prod.
Unfortunately the policy need to be manually edited to select again the validator.

**Comment by ablwr** [comment]
Yes this is fixed!
